### ISSUE TITLE
App is NOT WORKING. OOO tag is not set on tickets where the agent is set as unavailable.

### ISSUE THREAD

**Issue by mgradu** [zendesklabs/out_of_office_app#245] opened 2018-09-05 08:57 UTC
Hi guys,

We got an unpleasant surprise this morning when we noticed that even though an agent was set to unavailable, the "agent_ooo" tag was not set on their pending/on-hold/solved tickets. This means that we got no notifications when their tickets were updated, causing SLAs to be broken. Can you please investigate this? Our org name is "amplitude".

**Comment by Nebopolis** [comment] 2018-09-07 10:41
Hi @mgradu,

I think this may be a duplicate of https://github.com/zendesklabs/out_of_office_app/issues/242. As I said in that issue: 
> I've gotten some time to dig at this and for some reason wasn't able to replicate the issue on any test accounts. At this point I think it'd be best if you open a ticket with Zendesk support, and specify that the issue is a recent issue that appears to be framework related rather than app-specific. Feel free to CC me on the ticket (bevans@zendesk<dot>com). That way I'll be able to work with the support agent to more seamlessly debug things. I do have some plans on how to update the app to framework v2 that might help, but that is still a ways out on the timeline.

I know this is a bit of a runaround, but I'm not able to do deep enough troubleshooting on a public forum unfortunately. 

Finally, as a word of warning: If this does turn out to be a bug in the app itself, any fix will require substantial work to update the app to v2 of the framework before a fix can even be begun. Since I don't work on the app as part of my main job duties, there is no timeline or expected date for that.

- Thanks

**Closed as completed by Nebopolis** 2018-09-07 10:41 UTC
